# Introduction to Matrix

In [59]:
# What's a matrix?
# In R, a matrix is a collection of elements of the same data type (numeric, character, or logical) 
#arranged into a fixed number of rows and columns. Since you are only working with rows and columns, 
#a matrix is called two-dimensional.

# You can construct a matrix in R with the matrix() function. Consider the following example:

# matrix(1:9, byrow = TRUE, nrow = 3)
# In the matrix() function:

# The first argument is the collection of elements that R will arrange into the rows and columns of the matrix. 
#Here, we use 1:9 which is a shortcut for c(1, 2, 3, 4, 5, 6, 7, 8, 9).
# The argument byrow indicates that the matrix is filled by the rows. If we want the matrix to be 
#filled by the columns, we just place byrow = FALSE.
# The third argument nrow indicates that the matrix should have three rows.

# Code 2.01

In [60]:
# Construct a matrix with 3 rows that contain the numbers 1 up to 9
matrix(1:9,byrow = TRUE,nrow = 3)

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [61]:
# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Create box_office
box_office <- c(new_hope, empire_strikes, return_jedi)

# Construct star_wars_matrix
star_wars_matrix <- matrix(box_office,byrow = TRUE, nrow=3)
star_wars_matrix

[,1]    [,2] 
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

# Naming a Matrix

In [62]:
# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Construct matrix
star_wars_matrix <- matrix(c(new_hope, empire_strikes, return_jedi), nrow = 3, byrow = TRUE)

# Vectors region and titles, used for naming
region <- c("US", "non-US")
titles <- c("A New Hope", "The Empire Strikes Back", "Return of the Jedi")

# Name the columns with region
colnames(star_wars_matrix) <- region
# Name the rows with titles

rownames(star_wars_matrix) <- titles

# Print out star_wars_matrix

star_wars_matrix

US      non-US
A New Hope              460.998 314.4 
The Empire Strikes Back 290.475 247.9 
Return of the Jedi      309.306 165.8

# Code 2.02

In [63]:
vec1 <- c('Aravind',19,'27/07/1998','MALE',93.54,5.53,67)
vec2 <- c('Arun Sai Reddy',19,'19/06/1998','MALE',95.54,5.647,63)
vec3 <- c('Sai Vardhan',21,'21/05/1997','MALE',94.54,5.62,64)
vec4 <- c('Sri Manikanta Palakollu',19,'18/05/1999','MALE',98.54,5.63,61)

my_matrix <- matrix(c(vec1, vec2, vec3, vec4), byrow = TRUE, nrow = 4)
rollnumbers <- c('16D41A05C8', '16D41A05D8','16D41A05G5','16D41A05F0')
details <- c('Name', 'Age','Dateofbirth', 'Gender', 'Percentage', 'Height', 'Weight')

colnames(my_matrix) <- details
rownames(my_matrix) <- rollnumbers

print(my_matrix)

           Name                      Age  Dateofbirth  Gender Percentage
16D41A05C8 "Aravind"                 "19" "27/07/1998" "MALE" "93.54"   
16D41A05D8 "Arun Sai Reddy"          "19" "19/06/1998" "MALE" "95.54"   
16D41A05G5 "Sai Vardhan"             "21" "21/05/1997" "MALE" "94.54"   
16D41A05F0 "Sri Manikanta Palakollu" "19" "18/05/1999" "MALE" "98.54"   
           Height  Weight
16D41A05C8 "5.53"  "67"  
16D41A05D8 "5.647" "63"  
16D41A05G5 "5.62"  "64"  
16D41A05F0 "5.63"  "61"  


# Code 2.03

In [64]:
# Construct star_wars_matrix
box_office <- c(460.998, 314.4, 290.475, 247.900, 309.306, 165.8)
star_wars_matrix <- matrix(box_office, nrow = 3, byrow = TRUE,
                           dimnames = list(c("A New Hope", "The Empire Strikes Back", "Return of the Jedi"), 
                                           c("US", "non-US")))

# Calculate worldwide box office figures
worldwide_vector <- rowSums(star_wars_matrix)
worldwide_vector

A New Hope The Empire Strikes Back      Return of the Jedi 
                775.398                 538.375                 475.106

In [65]:
# Bind the new variable worldwide_vector as a column to star_wars_matrix
all_wars_matrix <- cbind(star_wars_matrix,worldwide_vector)

all_wars_matrix

US      non-US worldwide_vector
A New Hope              460.998 314.4  775.398         
The Empire Strikes Back 290.475 247.9  538.375         
Return of the Jedi      309.306 165.8  475.106

In [66]:
girlfriend <- c('Akshara','Varsha','Kavya','Harika')
mobile <- c(9848726190,8464342134,6300012376,9912575995)
cbind(my_matrix,girlfriend,mobile)

typeof(my_matrix)
class(my_matrix)

Name                    Age Dateofbirth Gender Percentage Height
16D41A05C8 Aravind                 19  27/07/1998  MALE   93.54      5.53  
16D41A05D8 Arun Sai Reddy          19  19/06/1998  MALE   95.54      5.647 
16D41A05G5 Sai Vardhan             21  21/05/1997  MALE   94.54      5.62  
16D41A05F0 Sri Manikanta Palakollu 19  18/05/1999  MALE   98.54      5.63  
           Weight girlfriend mobile    
16D41A05C8 67     Akshara    9848726190
16D41A05D8 63     Varsha     8464342134
16D41A05G5 64     Kavya      6300012376
16D41A05F0 61     Harika     9912575995

[1] "character"

[1] "matrix"

# Code 2.04

In [67]:
General <- c('Naveen',21,'02/10/1997','MALE',87.95,5.898,73,'Malaika',7984563984)
my_matrix <- rbind(my_matrix,General)
my_matrix

Warning message in rbind(my_matrix, General):
“number of columns of result is not a multiple of vector length (arg 2)”

Name                    Age Dateofbirth Gender Percentage Height
16D41A05C8 Aravind                 19  27/07/1998  MALE   93.54      5.53  
16D41A05D8 Arun Sai Reddy          19  19/06/1998  MALE   95.54      5.647 
16D41A05G5 Sai Vardhan             21  21/05/1997  MALE   94.54      5.62  
16D41A05F0 Sri Manikanta Palakollu 19  18/05/1999  MALE   98.54      5.63  
General    Naveen                  21  02/10/1997  MALE   87.95      5.898 
           Weight
16D41A05C8 67    
16D41A05D8 63    
16D41A05G5 64    
16D41A05F0 61    
General    73

# Code 2.05

In [48]:
# Total revenue for US and non-US
total_revenue_vector <- colSums(all_wars_matrix)
  
# Print out total_revenue_vector

total_revenue_vector

US           non-US worldwide_vector 
        1060.779          728.100         1788.879

# Matrix Arthimetic

In [54]:
randomvec1 <- seq(1,9)
randomvec2 <- seq(10,18)

my_matrix1 <- matrix(randomvec1,byrow = TRUE,nrow = 3)
my_matrix2 <- matrix(randomvec2,byrow = TRUE,nrow = 3)

my_matrix1
my_matrix2

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[,1] [,2] [,3]
[1,] 10   11   12  
[2,] 13   14   15  
[3,] 16   17   18

In [55]:
add <- my_matrix1 + my_matrix2

sub <- my_matrix2 - my_matrix1

mul <- my_matrix1 * my_matrix2

div <- my_matrix2 / my_matrix1

print(add)
print(sub)
print(mul)
print(div)

     [,1] [,2] [,3]
[1,]   11   13   15
[2,]   17   19   21
[3,]   23   25   27
     [,1] [,2] [,3]
[1,]    9    9    9
[2,]    9    9    9
[3,]    9    9    9
     [,1] [,2] [,3]
[1,]   10   22   36
[2,]   52   70   90
[3,]  112  136  162
          [,1]  [,2] [,3]
[1,] 10.000000 5.500  4.0
[2,]  3.250000 2.800  2.5
[3,]  2.285714 2.125  2.0
